### ISSUE TITLE
Add agent that can write to one of many possible topics

### ISSUE THREAD

**Issue by ksaurabh21** [LangStream/langstream#454]
Can we create an agent that needs to run some logic or call an external API and based on the results, it decides which topic to write to? For example an agent that need to call a REST API for a multiclass classification model, and based on model prediction, the agent decides which topic it will write to from a list of available topics.

**Comment by eolivelli** [comment]
I think that a good approach to provide this feature is to add some "topic-sink" that allows to dispatch the incoming message to a topic depending on some properties or values.

So in your case the custom agent may simply add a "property" (or "header") to the message with the destination and then the "topic-sink" will dispatch the message.

I am referring to a sink because a simple "processor" is required to have a single "input" and a single "output", because that's the model in the ExecutionPlan and having a processor that is able to by pass the pipeline configuration may lead to tricky situations.

**Comment by ksaurabh21** [comment]
That's a great idea. A dispatcher will solve this problem if it can route an incoming message to a topic based on some values or properties in the message itself.
